name: Execute and Convert Notebooks

# Trigger manually 
on: 
    workflow_dispatch:


jobs:
  prepare-and-execute-notebooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        notebook:  ["test"] #['compare_face_detection_accuracy.ipynb', 'compare_face_detection_efficacy.ipynb']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 
        
    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Execute and convert notebook
      run: |
        # CD to correct directory
        cd ${{ github.workspace }}
        # Creating the directory
        mkdir -p data/results
        # Execute the notebook in-place
        jupyter nbconvert --to notebook --execute test/${{ matrix.notebook }}.ipynb --inplace
        # Convert to HTML
        jupyter nbconvert --to html test/${{ matrix.notebook }}.ipynb --output test/${{ matrix.notebook }}.html
        # Convert to PDF
        jupyter nbconvert --to pdf test/${{ matrix.notebook }}.ipynb --output test/results/${{ matrix.notebook }}.pdf
      continue-on-error: true
        
    
    - name: Commit results
      if: success()
      run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b update-notebooks-${{ github.run_id }}
          git add .
          git commit -m "Automated notebook execution and conversion"
          # Set up Git to use the GitHub token for authentication
          git -c http.extraheader="AUTHORIZATION: bearer ${{ secrets.GITHUB_TOKEN }}" push origin update-notebooks-${{ github.run_id }}
    

  open-pull-request:
    needs: prepare-and-execute-notebooks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Open Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Automated Notebook Update"
        pr_body: "This PR includes executed notebooks and their conversions."
        source_branch: "update-notebooks-${{ github.run_id }}"
        destination_branch: "main" 